[package]
name = "sekas-server"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "The Sekas server."

[dependencies]
sekas-api = { path = "../api", version = "0.5" }
sekas-client = { path = "../client", version = "0.5" }
sekas-macro = { path = "../macro", version = "0.5" }
sekas-rock = { path = "../rock", version = "0.5" }
sekas-runtime = { path = "../runtime", version = "0.5" }
sekas-schema = { path = "../schema", version = "0.5" }

# optional layers
sekas-etcd-proxy = { path = "../../layers/etcd", optional = true }

async-stream.workspace = true
crc32fast.workspace = true
derivative.workspace = true
futures.workspace = true
lazy_static.workspace = true
log.workspace = true
paste.workspace = true
prometheus = { workspace = true, features = ["process"] }
prometheus-static-metric.workspace = true
prost.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
num_cpus.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true

const-str = "0.4"
dashmap = "5.4"
http-body = "0.4"
hyper = "0.14"
libc = "0.2"
pest = "2.7"
pin-project = "1"
uuid = { version = "1.1", features = ["v4"] }
sysinfo = "0.26"
tokio-util = { version = "0.7", features = ["time"] }
url = "2.3"

[dependencies.raft]
git = "https://github.com/w41ter/raft-rs.git"
features = ["prost-codec", "default-logger"]
default-features = false
branch = "prost-0.11"

[dependencies.raft-engine]
git = "https://github.com/w41ter/raft-engine.git"
default-features = false
features = ["prost"]
branch = "prost-0.11"

[dependencies.rocksdb]
git = "https://github.com/w41ter/rust-rocksdb.git"
features = ["multi-threaded-cf", "serde1"]
branch = "v8.8.1-patched"

[build-dependencies]
prost-build.workspace = true
tonic-build.workspace = true
protoc-build.workspace = true

[features]
layer_etcd = ["dep:sekas-etcd-proxy"]

[dev-dependencies]
ctor = "0.1"
quote = "1.0"
rand = { version = "0.8", features = ["small_rng"] }
reqwest = { version = "0.11", features = ["json"] }
socket2 = "0.5"
syn = "2.0"
tempdir = "0.3"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }

